In [1]:
import importlib
import numpy as np
from sympy import *

import SymplecticMatroids
importlib.reload(SymplecticMatroids)

<module 'SymplecticMatroids' from '/home/buchi1002/work/lab/SymplecticMatroids/SymplecticMatroids.py'>

In [3]:
n = 3
J = SymplecticMatroids.make_base(3)

[-3, -2, -1, 1, 2, 3]

### admissible subsets

In [4]:
n = 3
k = 2

Jk = SymplecticMatroids.make_admissible_subsets(n,k)

print(len(Jk))
print(*Jk)

12
[1, 2] [-2, 1] [-1, 2] [-2, -1] [1, 3] [-3, 1] [-1, 3] [-3, -1] [2, 3] [-3, 2] [-2, 3] [-3, -2]


### admissible permutations

In [5]:
n = 3
W3 = SymplecticMatroids.make_admissible_permutations(n)

print(len(W3))
W3[3]

48


(3, 2, -1, 1, -2, -3)

### admissible ordering

In [6]:
w = W3[10]

w_order = SymplecticMatroids.make_admissible_ordering(w)

print(w)
print(w_order)

(-2, 3, -1, 1, -3, 2)
{-2: -3, 3: -2, -1: -1, 1: 1, -3: 2, 2: 3}


In [7]:
array = [1,1,2,3,2,1]

print(w_order)
print(array)
sorted([1,1,2,3,2,1], key = lambda x:w_order[x])

{-2: -3, 3: -2, -1: -1, 1: 1, -3: 2, 2: 3}
[1, 1, 2, 3, 2, 1]


[3, 1, 1, 1, 2, 2]

### symplectic matroids

In [8]:
import itertools

Jk = SymplecticMatroids.make_admissible_subsets(3,2)

len_Basis = 4
candidate_basis = list(list(s) for s in itertools.combinations(Jk, len_Basis))

print(len(candidate_basis))
candidate_basis

495


[[[1, 2], [-2, 1], [-1, 2], [-2, -1]],
 [[1, 2], [-2, 1], [-1, 2], [1, 3]],
 [[1, 2], [-2, 1], [-1, 2], [-3, 1]],
 [[1, 2], [-2, 1], [-1, 2], [-1, 3]],
 [[1, 2], [-2, 1], [-1, 2], [-3, -1]],
 [[1, 2], [-2, 1], [-1, 2], [2, 3]],
 [[1, 2], [-2, 1], [-1, 2], [-3, 2]],
 [[1, 2], [-2, 1], [-1, 2], [-2, 3]],
 [[1, 2], [-2, 1], [-1, 2], [-3, -2]],
 [[1, 2], [-2, 1], [-2, -1], [1, 3]],
 [[1, 2], [-2, 1], [-2, -1], [-3, 1]],
 [[1, 2], [-2, 1], [-2, -1], [-1, 3]],
 [[1, 2], [-2, 1], [-2, -1], [-3, -1]],
 [[1, 2], [-2, 1], [-2, -1], [2, 3]],
 [[1, 2], [-2, 1], [-2, -1], [-3, 2]],
 [[1, 2], [-2, 1], [-2, -1], [-2, 3]],
 [[1, 2], [-2, 1], [-2, -1], [-3, -2]],
 [[1, 2], [-2, 1], [1, 3], [-3, 1]],
 [[1, 2], [-2, 1], [1, 3], [-1, 3]],
 [[1, 2], [-2, 1], [1, 3], [-3, -1]],
 [[1, 2], [-2, 1], [1, 3], [2, 3]],
 [[1, 2], [-2, 1], [1, 3], [-3, 2]],
 [[1, 2], [-2, 1], [1, 3], [-2, 3]],
 [[1, 2], [-2, 1], [1, 3], [-3, -2]],
 [[1, 2], [-2, 1], [-3, 1], [-1, 3]],
 [[1, 2], [-2, 1], [-3, 1], [-3, -1]],
 [[1, 2]

In [9]:
w_orderings = dict()
for w in W3:
    w_orderings[w] = SymplecticMatroids.make_admissible_ordering(w)

In [10]:
w_orderings[(2, -3, -1, 1, 3, -2)]

{2: -3, -3: -2, -1: -1, 1: 1, 3: 2, -2: 3}

In [11]:
symplectic_matroids = list()
for candidate in candidate_basis:

    # 任意のwで極大なものが存在
    flag0 = True
    for w_order in w_orderings:
        # wに対してあるAが存在して極大
        flag1 = False
        for idxA in range(len(candidate)):
            A = candidate[idxA].copy()
            A.sort(key= lambda x:w_order[x])

            # Aが極大
            flag2 = True
            for idxB in range(len(candidate)):
                B = candidate[idxB].copy()
                B.sort(key= lambda x:w_order[x])
                for i in range(k):
                    if w_order[A[i]] < w_order[B[i]]:
                        flag2 = False
                        break

                if not flag2:
                    break
            flag1 = flag1 or flag2

        flag0 = flag0 and flag1
        if not flag1:
            break

    if flag0:
        symplectic_matroids.append(candidate)



In [12]:
print(len(symplectic_matroids))
symplectic_matroids

130


[[[1, 2], [-2, 1], [-1, 2], [-2, -1]],
 [[1, 2], [-2, 1], [1, 3], [-3, 1]],
 [[1, 2], [-2, 1], [1, 3], [-2, 3]],
 [[1, 2], [-2, 1], [1, 3], [-3, -2]],
 [[1, 2], [-2, 1], [-3, 1], [-2, 3]],
 [[1, 2], [-2, 1], [-3, 1], [-3, -2]],
 [[1, 2], [-2, 1], [2, 3], [-2, 3]],
 [[1, 2], [-2, 1], [2, 3], [-3, -2]],
 [[1, 2], [-2, 1], [-3, 2], [-2, 3]],
 [[1, 2], [-2, 1], [-3, 2], [-3, -2]],
 [[1, 2], [-2, 1], [-2, 3], [-3, -2]],
 [[1, 2], [-1, 2], [-2, -1], [-2, 3]],
 [[1, 2], [-1, 2], [-2, -1], [-3, -2]],
 [[1, 2], [-1, 2], [1, 3], [-1, 3]],
 [[1, 2], [-1, 2], [1, 3], [-3, -1]],
 [[1, 2], [-1, 2], [-3, 1], [-1, 3]],
 [[1, 2], [-1, 2], [-3, 1], [-3, -1]],
 [[1, 2], [-1, 2], [2, 3], [-3, 2]],
 [[1, 2], [1, 3], [-3, 1], [2, 3]],
 [[1, 2], [1, 3], [-3, 1], [-3, 2]],
 [[1, 2], [1, 3], [-3, 1], [-2, 3]],
 [[1, 2], [1, 3], [-3, 1], [-3, -2]],
 [[1, 2], [1, 3], [2, 3], [-3, 2]],
 [[1, 2], [1, 3], [2, 3], [-2, 3]],
 [[1, 2], [1, 3], [2, 3], [-3, -2]],
 [[1, 2], [1, 3], [-3, 2], [-2, 3]],
 [[1, 2], [1, 3], [

In [13]:
symplectic_matroids = list()
for candidate in candidate_basis:

    # 任意のwで極大なものが存在
    flag0 = True
    for w_order in w_orderings:
        # wに対してあるAが存在して極大
        flag1 = False
        for idxA in range(len(candidate)):
            A = candidate[idxA].copy()
            A.sort(key= lambda x:w_order[x])

            # Aが極大
            flag2 = True
            for idxB in range(len(candidate)):
                B = candidate[idxB].copy()
                B.sort(key= lambda x:w_order[x])
                for i in range(k):
                    if w_order[A[i]] < w_order[B[i]]:
                        flag2 = False
                        break

                if not flag2:
                    break
            flag1 = flag1 or flag2

        flag0 = flag0 and flag1
        if not flag1:
            break

    if flag0:
        symplectic_matroids.append(candidate)

## 3元体上の representable symplectic matroids の isotropic subspace

In [110]:
S = SymplecticMatroids.make_isotropic_subspace(3,4,4)

KeyboardInterrupt: 

### 2-homogeneous matroid

In [5]:
li_candidate_h24 = list()
for space in S:
    m = np.linalg.matrix_rank(space[0], tol=None)
    l = np.linalg.matrix_rank(space[1], tol=None)
    if m == 2 and l == 2:
        M = np.hstack((space[0], space[1]))
        print(Matrix(M).rref())
        print("-----------")
        li_candidate_h24.append(M)

(Matrix([
[0, 1, 0, 1, 0, 0, 0, 0],
[0, 0, 1, 1, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 0, 0],
[0, 0, 0, 0, 0, 1, 1, 2]]), (1, 2, 4, 5))
-----------
(Matrix([
[1, 2, 0, 0, 0, 0, 0, 0],
[0, 0, 1, 1, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 1, 0, 0],
[0, 0, 0, 0, 0, 0, 1, 2]]), (0, 2, 4, 6))
-----------
(Matrix([
[0, 1, 0, -1, 0, 0, 0, 0],
[0, 0, 1,  2, 0, 0, 0, 0],
[0, 0, 0,  0, 1, 0, 0, 0],
[0, 0, 0,  0, 0, 1, 1, 1]]), (1, 2, 4, 5))
-----------
(Matrix([
[0, 1, 0, -1, 0, 0, 0, 0],
[0, 0, 1,  2, 0, 0, 0, 0],
[0, 0, 0,  0, 1, 0, 0, 0],
[0, 0, 0,  0, 0, 1, 1, 1]]), (1, 2, 4, 5))
-----------
(Matrix([
[0, 1, 0, -1, 0, 0, 0, 0],
[0, 0, 1,  2, 0, 0, 0, 0],
[0, 0, 0,  0, 1, 0, 0, 0],
[0, 0, 0,  0, 0, 1, 1, 1]]), (1, 2, 4, 5))
-----------
(Matrix([
[0, 1, 0, -1, 0, 0, 0, 0],
[0, 0, 1,  2, 0, 0, 0, 0],
[0, 0, 0,  0, 1, 0, 0, 0],
[0, 0, 0,  0, 0, 1, 1, 1]]), (1, 2, 4, 5))
-----------
(Matrix([
[0, 1, 0, -1, 0, 0, 0, 0],
[0, 0, 1,  2, 0, 0, 0, 0],
[0, 0, 0,  0, 1, 0, 0, 0],
[0, 0, 0,  0, 0, 1, 1, 1]]), (1, 2, 4, 5)

In [47]:
import itertools

N = 4
k = 2
Lefts = tuple(range(1,N+1))
Starreds = tuple(itertools.product((1,-1), repeat=k))

Jk = list()
for left in itertools.combinations(Lefts, k):
    for starred in Starreds:
        K = tuple(left[i]*starred[i] for i in range(k))

        Jk.append(K)

[(1, 2),
 (1, -2),
 (-1, 2),
 (-1, -2),
 (1, 3),
 (1, -3),
 (-1, 3),
 (-1, -3),
 (1, 4),
 (1, -4),
 (-1, 4),
 (-1, -4),
 (2, 3),
 (2, -3),
 (-2, 3),
 (-2, -3),
 (2, 4),
 (2, -4),
 (-2, 4),
 (-2, -4),
 (3, 4),
 (3, -4),
 (-3, 4),
 (-3, -4)]

# ～～ Symplectic $U_{k, n}$ 表現探索の旅 ～～

## $U_{k,n}$ 表現の全探索

In [88]:
import numpy as np
import itertools

import SymplecticMatroids


p = 5
n = 4
k = 2

In [89]:
def det(M):
    M = [row[:] for row in M] # make a copy to keep original M unmodified
    N, sign, prev = len(M), 1, 1
    for i in range(N-1):
        if M[i][i] == 0: # swap with another row having nonzero i's elem
            swapto = next( (j for j in range(i+1,N) if M[j][i] != 0), None )
            if swapto is None:
                return 0 # all M[*][i] are zero => zero determinant
            M[i], M[swapto], sign = M[swapto], M[i], -sign
        for j in range(i+1,N):
            for k in range(i+1,N):
                assert ( M[j][k] * M[i][i] - M[j][i] * M[i][k] ) % prev == 0
                M[j][k] = ( M[j][k] * M[i][i] - M[j][i] * M[i][k] ) // prev
        prev = M[i][i]
    return sign * M[-1][-1]

In [90]:
Fk = list(itertools.product(range(p), repeat=k))
Fk = np.array(list(map(lambda x:np.array(x), Fk)))

d_det = dict()
for t_idx in itertools.combinations_with_replacement(range(len(Fk)), k):
    d_det[t_idx] = det(Fk[list(t_idx)])%p

In [92]:
matrices = itertools.combinations_with_replacement(range(len(Fk)),n)
matrices = list(map(lambda x:np.array(x) , matrices))
matrices = matrices[1:] # 0行列はいらない

subset_indeces = tuple(itertools.combinations(range(n),k))

v_U_kn = list()
for matrix in matrices:
    flag = True
    for idx in subset_indeces:
        if d_det[tuple(matrix[list(idx)])] == 0:
            flag = False
            break
    if flag:
        v_U_kn.append(matrix)


In [93]:
print(len(v_U_kn))
print(Fk[list(v_U_kn[5])].T)

3840
[[0 1 1 2]
 [1 0 1 4]]


In [94]:
U_kn = [np.array([np.array([0 for _ in range(k)]) for i in range(n)]) for j in range(len(v_U_kn))]

for u in range(len(U_kn)):
    for idx in range(n):
        U_kn[u][idx] = Fk[v_U_kn[u][idx]]

In [95]:
print(len(U_kn))
print(U_kn[5].T)

3840
[[0 1 1 2]
 [1 0 1 4]]


In [96]:
candidate0 = list()
for idxA, idxB in itertools.combinations(range(len(U_kn)), 2):
    ABt = (U_kn[idxA].T@U_kn[idxB])%p
    if np.array_equal(ABt, ABt.T):
        candidate0.append((v_U_kn[idxA],v_U_kn[idxB]))

In [97]:
print("A")
print(Fk[list(candidate0[5][0])].T)

print("B")
print(Fk[list(candidate0[5][1])].T)

print("ABt")
print(Fk[list(candidate0[5][0])].T@Fk[list(candidate0[5][1])]%p)

print(len(candidate0))

A
[[0 1 1 1]
 [1 0 1 2]]
B
[[0 1 1 2]
 [1 0 3 2]]
ABt
[[4 0]
 [0 3]]
1487990


In [98]:
admissible_subsets = SymplecticMatroids.make_admissible_subsets(n,k)

for X in admissible_subsets:
    for e in range(len(X)):
        if X[e] > 0:
            X[e] = X[e] - 1
        else:
            X[e] = n-1 - X[e]
    X.sort()

In [99]:
candidate1 = list()
for AB in candidate0:
    flag = True
    A_B = np.hstack(AB)
    for X in admissible_subsets:
        if d_det[tuple(sorted(A_B[X]))] == 0:
            flag = False
            break
    if flag:
        candidate1.append(AB)

In [121]:
X = admissible_subsets[10]
print("admmissible subset")
print(X)
print()

print("candidate (A B)")
print(Fk[np.hstack(candidate1[5])].T)
print()

print("candidate (A B)[X]")
print(Fk[np.hstack(candidate1[5])][X].T)
print()

print("det|(A B)[X]|")
print(det(Fk[np.hstack(candidate1[5])][X]))
print()

print("the number of candidates")
print(len(candidate1))

admmissible subset
[3, 4]

candidate (A B)
[[0 1 1 1 0 1 2 3]
 [1 0 1 2 1 0 1 2]]

candidate (A B)[X]
[[1 0]
 [2 1]]

det|(A B)[X]|
1

the number of candidates
192198


In [126]:
admissible_subsets = set(map(tuple, admissible_subsets))

subsets = set(itertools.combinations(range(2*n), k))
non_admissible_subsets = subsets - admissible_subsets

candidate2 = list()
for AB in candidate1:
    A_B = np.hstack(AB)
    flag = True
    for X in non_admissible_subsets:
        if  d_det[tuple(sorted(A_B[list(X)]))] != 0:
            flag = False
            break

    if flag:
        candidate2.append((A,B))

In [129]:
non_admissible_subsets

{(0, 4), (1, 5), (2, 6), (3, 7)}

In [135]:
X = list(tuple(non_admissible_subsets)[3])
print("non_admmissible subset")
print(X)
print()

print("candidate (A B)")
print(Fk[np.hstack(candidate2[5])].T)
print()

print("candidate (A B)[X]")
print(Fk[np.hstack(candidate2[5])][X].T)
print()

print("det|(A B)[X]|")
print(det(Fk[np.hstack(candidate2[5])][X]))
print()

print("the number of candidates")
print(len(candidate2))

non_admmissible subset
[1, 5]

candidate (A B)
[[0 1 1 1 0 1 1 2]
 [1 0 1 2 1 0 1 4]]

candidate (A B)[X]
[[1 1]
 [0 0]]

det|(A B)[X]|
0

the number of candidates
65972


In [136]:
candidate3 = list()
for A, B in candidate2:
    At = Fk[A]
    Bt = Fk[B]

    flag0 = False # [ある列i, i* が存在して独立]
    for i in range(n):
        flag1 = True # [任意のスカラー倍でベクトルが等しくない(独立)]
        for k in range(p):
            if np.array_equal(At[i],k*Bt[i]%p):
               flag1 = False
               break

        if flag1:
            flag0 = True
            break
    
    if flag0:
        candidate3.append((A,B))

In [137]:
print(candidate3)

[]


つまり、存在しない。