# **Find Symplectic Matroids**

## **Preliminary**

In [1]:
import numpy as np
import random

import symplectic_matroids

#### ***ground set***
$J = \{1,\ \cdots\ n\} \cup \{-1,\ \cdots\ -n\}$

In [2]:
n = 3
k = 2
Jk = symplectic_matroids.make_admissible_subsets(n,k)
print(Jk)

[[1, 2], [-2, 1], [-1, 2], [-2, -1], [1, 3], [-3, 1], [-1, 3], [-3, -1], [2, 3], [-3, 2], [-2, 3], [-3, -2]]


**Remark** : on the ground set, 

$$-n < \cdots < -2 < -1 < 1 < 2 < \cdots < n$$

holds.

### ***admissible subsets***

**Definition** : *admissible subset*

$X = \{x_1, x_2, \cdots x_k\} \subset J$ is admissilesubsets if and only if 
$$\{x_1, _2, \cdots x_k\} \cap \{-x_1, -x_2, \cdots -x_k\} = \emptyset$$
holds.

$J_k$ : a family of admissible subset of $J = \{1, 2, \cdots n\}$

In [3]:
n = 3
k = 2

J = symplectic_matroids.make_ground_set(n)
Jk = symplectic_matroids.make_admissible_subsets(n,k)

print("params")
print("n = " + str(n) + ", k = " + str(k))
print("ground set")
print(J)
print("a family of admissible subset")
print(*Jk)

params
n = 3, k = 2
ground set
[-3, -2, -1, 1, 2, 3]
a family of admissible subset
[1, 2] [-2, 1] [-1, 2] [-2, -1] [1, 3] [-3, 1] [-1, 3] [-3, -1] [2, 3] [-3, 2] [-2, 3] [-3, -2]


### ***admissible permutations***

**Definition**: *admissible permutation*

The permutation $w:J \to J$ is admissible permutation if and only if
$$\forall x \in J,\ w(-x) = -w(x)$$
holds

$W$ : a set of admissible permutation on $J$

In [4]:
n = 3
W = symplectic_matroids.make_admissible_permutations(n)
randomint = random.randrange(len(W))

print("the number of admissible permutation")
print(len(W))
print("the example of admissible permutation")
print(W[0])
print(W[randomint])

the number of admissible permutation
48
the example of admissible permutation
(-3, -2, -1, 1, 2, 3)
(1, -2, 3, -3, 2, -1)


### **admissible ordering**

**Definition** : *admissible ordering*
An ordering made from admissible permutation is admissible ordering. In other words, 

we set $w \in W$, admissible orderings $\leq^{w}$ satisfy

$x \leq^{w} y \Leftrightarrow w(x)^{-1} \leq w(y)^{-1}$.


**Remark** : we use $\prec$ instead of $\leq^{w}$

In [5]:
randomint = random.randrange(len(W))
w = W[randomint]

w_order = symplectic_matroids.make_admissible_ordering(w)

print("an admissible permutation")
print(W[0])
print(w)
print("an admissible ordering")
print(w_order)

an admissible permutation
(-3, -2, -1, 1, 2, 3)
(2, 1, -3, 3, -1, -2)
an admissible ordering
{2: -3, 1: -2, -3: -1, 3: 1, -1: 2, -2: 3}


#### (sort with an admissible ordering)

In [6]:
array = [1,-1,-2,3,2,1, -3]

print(array)
print("sorted by the admissible orderings from")
print(W[0])
print(w)
print("sorted array")
print(sorted(array, key = lambda x:w_order[x]))

[1, -1, -2, 3, 2, 1, -3]
sorted by the admissible orderings from
(-3, -2, -1, 1, 2, 3)
(2, 1, -3, 3, -1, -2)
sorted array
[2, 1, 1, -3, 3, -1, -2]


### ***symplectic matroids***

Groundset : $J$

Base : $\mathcal{B} \subset J_k$

**Definition** : ***symplectic matroids***

the triple $(J,\ -,\ \mathcal{B})$ is symplectic matroids if and only $\forall \prec\ \in W$, there exists optimal set. i.e. $\exist O \in \mathcal{B}$ such that
$$ \forall B \in \mathcal{B},\ B \prec O.$$

Remark : $B \prec O$ means
$$B = \{b_1 \prec \cdots\ \prec b_k\},\ O = \{o_1 \prec \cdots \prec o_k\}$$
$$b_1 \prec o_1$$
$$b_2 \prec b_2$$
$$\vdots$$
$$b_n \prec o_k$$
holds.

## **Construction of Symplectic Matroids**

In [19]:
# the number of elements of bases
n_elements = 4

# all of the bases of the symplectic matroids
bases = symplectic_matroids.make_base(n, k, n_elements)

In [23]:
randomint = random.randrange(len(bases))

print("the number of symplectic matroids with "+ str(n_elements) + " elements")
print(len(bases))
print("example of bases")
print(bases[randomint])

the number of symplectic matroids with 4 elements
130
example of bases
[[-1, 3], [-3, -1], [2, 3], [-3, 2]]


## **Representable Symplectic Matroids**

In [13]:
import importlib
import numpy as np
from sympy import *

import symplectic_matroids
importlib.reload(symplectic_matroids)

<module 'symplectic_matroids' from '/home/buchi1002/work/lab/SymplecticMatroids/symplectic_matroids.py'>

**Theorem** : *representable symplectic matroids*

We assume $A = (\bm{a}_1\ \cdots\ \bm{a}_n), B = (\bm{b}_1\ \cdots\ \bm{b}_n) \in \mathbb{F}_{q}^{k \times n},\ \text{rank}(A \mid B) = k,\ AB^T = BA^T$, 

$i \in \{1, \cdots, n\}$ column index $i$ means $\bm{a}_i$ $-i$ means $\bm{b}_i$.

We define $\mathcal{B} = \{B \in J_k \mid \forall X \in J_k,\ \text{det}(A \mid B)[X] \neq 0\}$, then $(J,\ -,\ \mathcal{B})$ is symplectic matroids.

**Remark** : $(A \mid B)[X]$ means the restriction of $(A \mid B)$ by $X$ column. 

eg ) $X = \{1, 5, -2\}$, then $(A \mid B)[X] = (\bm{a}_1, \bm{a}_5, \bm{b}_2)$

**Remark** : the symplectic matroids is called ***representable_symplectic_matroids***

**Remark** : the row space of $(A \mid B)$ (satisfing avove condition) is called ***isotropic subspace***

In [14]:
q = 3
n = 3
k = 4

S = symplectic_matroids.make_isotropic_subspace(q,n,k, limit = 10000)

In [15]:
print("the number of S")
print(len(S))

the number of S
10000


In [16]:
print("A")
print(S[5][0])

print("B")
print(S[5][1])

print("ABt")
print(S[5][0]@S[5][1].T%q)

A
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
B
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 2 0]]
ABt
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


**Lemma** : ***trivial representation***

We assume $\text{rank}A = k$ and $D \in \mathbb{F}^{n \times n}$ is diagonal matrix. if $B = AD$, $(A \mid B)$ is representation of symplectic matroids.

**Proof** : 

$A(AD)^T = A(D^TA^T) = (AD)A^T$